language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

cache: pip

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  # SpiNNakerManchester internal dependencies; development mode
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMan.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/PACMAN.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/DataSpecification.git@master
install:
  # These things ought to be enough
  - pip install -r requirements-test.txt
  - python ./setup.py install
script:
  - py.test unittests
  - py.test integration_tests
  - flake8 spinn_front_end_common
  - flake8 unittests integration_tests
