language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

cache: pip

install:
  # Install separately as it takes a long time
  - pip install 'numpy>=1.12'
  # SpiNNakerManchester internal dependencies; development mode
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMan.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/PACMAN.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/DataSpecification.git@master
  # These things ought to be enough
  - pip install -r requirements-test.txt
  - python ./setup.py install
script:
  - py.test unittests
  - py.test integration_tests
  - flake8 spinn_front_end_common
  - flake8 unittests integration_tests
